ALTER TABLE answer ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE category ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE question ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
