CREATE TABLE round (
  id SERIAL PRIMARY KEY,
  category_id INT NOT NULL REFERENCES category,
  is_joker_used BOOLEAN NOT NULL DEFAULT FALSE,
  start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  end_time TIMESTAMP NULL
);