DROP TABLE answer CASCADE;
DROP TABLE category CASCADE;
DROP TABLE player CASCADE;
DROP TABLE question CASCADE;
DROP TABLE round_question CASCADE;
DROP TABLE round CASCADE;
DROP TABLE user_account CASCADE;
